version: "3.5"

services:
  pulsar:
    image: apachepulsar/pulsar:3.0.2
    command: ["bin/pulsar", "standalone", "--no-functions-worker", "--no-stream-storage"]

  nodered:
    build: .
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data

volumes:
  nodered:
    name: nodered